# This script generates a list (HBW taxonomy) of species whose birdlife ranges 
# (2019) overlap neotropical forest terrestrial ecoregions

##### Script dependencies: species_lists.R #####

# housekeeping ----
library(sf)
`%ni%` <- Negate(`%in%`)

###### Get mainland neotropical forest polygon #####
# Continents shapefile:
cont <- rgdal::readOGR("/Users/jacobsocolar/Dropbox/Work/Useful_data/Map_data/Continents/continent.shp", 
                       p4s="+proj=longlat +datum=WGS84")
crs <- sp::CRS(sp::proj4string(cont))
# Get North American mainland
C <- 4    # N. America is continent 4
areas <- vector()  # Vector to hold area of each polygon in N. America
for(i in 1:length(cont[C,]@polygons[[1]]@Polygons)){
  areas[i] <- cont[C,]@polygons[[1]]@Polygons[[i]]@area
}
top <- order(areas)[length(areas)]   # The largest polygon will be the mainland
p <- sp::Polygon(cont[C,]@polygons[[1]]@Polygons[[top]]@coords)
N.ps <-sp:: Polygons(list(p), 1)
N.Am <- sp::SpatialPolygons(list(N.ps), proj4string=crs)

C <- 6      # S. America is continent 6
areas <- vector()
for(i in 1:length(cont[C,]@polygons[[1]]@Polygons)){
  areas[i] <- cont[C,]@polygons[[1]]@Polygons[[i]]@area
}
top <- order(areas)[length(areas)]
p <- sp::Polygon(cont[C,]@polygons[[1]]@Polygons[[top]]@coords)
S.ps <- sp::Polygons(list(p), 1)
S.Am <- sp::SpatialPolygons(list(S.ps), proj4string=crs)

NS.Am <- st_as_sf(rgeos::gUnion(S.Am, N.Am)) # American mainland sf

# Get neotropical forest ecoregions
ecoregions <- st_read("/Users/jacobsocolar/Dropbox/Work/Useful_data/Map_data/WWF_ecoregions/wwf_terr_ecos.shp")
neotrop.for.americas <- st_union(ecoregions[(ecoregions$REALM %in% c("NA", "NT")) & (ecoregions$BIOME %in% c(1:2)),])

# Find intersection of neotropical forest ecoregions and the American mainland
mainland.neotrop.forests1 <- st_intersection(NS.Am, neotrop.for.americas)

# Mask out isolated bits of tropical forest on peninsular Florida and Baja California
florida_mask <- st_read('/Users/jacobsocolar/Dropbox/Work/Useful_data/Map_data/WWF_ecoregions/nf_masks/florida_mask.kml')
baja_mask <- st_read('/Users/jacobsocolar/Dropbox/Work/Useful_data/Map_data/WWF_ecoregions/nf_masks/baja_mask.kml')
combined_mask <- st_union(florida_mask, baja_mask)
mainland.neotrop.forests <- st_difference(mainland.neotrop.forests1, combined_mask)

#plot(mainland.neotrop.forests[,1])

##### Get species list by intersecting BirdLife maps with the polygon #####
load("Data/GIS/birdlife_maps/recast_range_maps.Rdata") # generated by Species_lists.R

recast_range_maps$neotropF <- NA
for(i in 1:nrow(recast_range_maps)){
  print(i)
  recast_range_maps$neotropF[i] <- (sum(st_intersects(recast_range_maps[i,], mainland.neotrop.forests, sparse = F)) > 0)
}

nf_species <- as.character(unique(recast_range_maps$SCINAME[recast_range_maps$neotropF]))

save(nf_species, file = '/Users/jacobsocolar/Dropbox/Work/Useful_data/BirdlifeTraits/nf_species.Rdata')
